### ISSUE TITLE
IO Error with MagiskGApps

### ISSUE THREAD

**Issue by MarkusTieger** [chiteroman/PlayIntegrityFix#174]
When using this module and "MagiskGApps" (uses NikGApps as base), a error accoures, which leads to the crash of the google play services.
(No problems with "MindTheGapps", unsure if it is a "NikGApps" problem, but the module itself is very useful because you can really easy uninstall GApps, which i will, after the wearable api is implemented in microG btw).

Logcat:
```
12-16 21:20:12.527  8960  8960 W ziparchive: Unable to open '/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCoreSc.apk': No such file or directory
12-16 21:20:12.527  8960  8960 E .gms.persistent: Failed to open APK '/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCoreSc.apk': I/O error
12-16 21:20:12.527  8960  8960 E ResourcesManager: failed to add asset path '/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCoreSc.apk'
12-16 21:20:12.527  8960  8960 E ResourcesManager: java.io.IOException: Failed to load asset path /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCoreSc.apk
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.content.res.ApkAssets.nativeLoad(Native Method)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.content.res.ApkAssets.<init>(ApkAssets.java:296)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:145)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:472)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ResourcesManager.-$$Nest$mloadApkAssets(Unknown Source:0)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:167)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:548)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:630)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:682)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ResourcesManager.createResources(ResourcesManager.java:1028)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ResourcesManager.getResources(ResourcesManager.java:1131)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.LoadedApk.getResources(LoadedApk.java:1371)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3090)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3082)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6702)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.os.Looper.loopOnce(Looper.java:201)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.os.Looper.loop(Looper.java:288)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at java.lang.reflect.Method.invoke(Native Method)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-16 21:20:12.527  8960  8960 E ResourcesManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
12-16 21:20:12.529  8960  8960 D AndroidRuntime: Shutting down VM
```
I can confirm, that the filepath exists (with adb shell as root and ls). I have no clue why that error happens. Tested on Core and Basic. (Variants of NikGApps)
Disabling "PlayIntegrityFix" fixes the issue.

Magisk: 26.4-kitsune (a fork of magisk: Kitsune Mask)
PlayIntegrityFix: 14.4
Android: 13 (LineageOS)

**Comment by MarkusTieger** [comment]
Could also be a issue of the new LineageOS version. I haven't tested PlayIntegrityFix with that.

**Comment by MarkusTieger** [comment]
Fixed by 14.5

**Comment by MrMEEE** [comment]
I´m still seeing this issue on 15.9.6..

**Comment by diabl0w** [comment]
Could you reference how this was fixed? I am having the same issue with a different module

**Comment by diabl0w** [comment]
disregard... for Googlers: if you used magiskmount to add an apk to system, you can't have that apk in the magisk/zygisk denylist as it won't have access to its own directories. In hindsight, its obvious, but easy to not think about that while you're configuring the denylist
